// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaZ0E4xmCpU0wPUx8pfPoo-vchw6RH9us',
    appId: '1:438168052516:web:c9d264ac371aca0f3ac9b1',
    messagingSenderId: '438168052516',
    projectId: 'parkmywheels-1f3da',
    authDomain: 'parkmywheels-1f3da.firebaseapp.com',
    storageBucket: 'parkmywheels-1f3da.firebasestorage.app',
    measurementId: 'G-322XPZ8XBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwllhj7f406OG7zC3ahy3017pkta5Cgik',
    appId: '1:438168052516:android:6f7e7830308538503ac9b1',
    messagingSenderId: '438168052516',
    projectId: 'parkmywheels-1f3da',
    storageBucket: 'parkmywheels-1f3da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZQlIZK2fS6rhMMisYcPXwzsHmTPCOlc4',
    appId: '1:438168052516:ios:7a6b1e2b41b4bc473ac9b1',
    messagingSenderId: '438168052516',
    projectId: 'parkmywheels-1f3da',
    storageBucket: 'parkmywheels-1f3da.firebasestorage.app',
    androidClientId: '438168052516-fa1b7m1bur91nnap3qco5smethr4i421.apps.googleusercontent.com',
    iosBundleId: 'com.park.mywheels',
  );

}